title: "Alex's Derkach Blog"
header_title: "@alexsderkach"
description: My experiences and thoughts
email: your-email@domain.com
author: "alexsderkach"

social:
  name: Alex Derkach
  links:
    - https://twitter.com/alexsderkach
    - https://www.facebook.com/alexsderkach
    - https://www.linkedin.com/in/alexsderkach
    - https://github.com/alexsderkach
twitter:
  username: alexsderkach
github:
  username: alexsderkach
author:
  twitter: alexsderkach
logo: /assets/me.png

permalink: /:title/
url: http://alexsderkach.io

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-octicons

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

google_analytics: UA-94002520-1
disqus:
  shortname: alexsderkach

include: [CNAME]